# Generated by Django 3.0.5 on 2020-12-29 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tree_app', '0002_auto_20201229_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTreeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pin_code', models.IntegerField()),
                ('tree_girth', models.IntegerField()),
                ('time_of_logging', models.DateTimeField()),
                ('logged_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('logged_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree_app.TreeModel')),
            ],
            options={
                'verbose_name': 'Log Tree Model',
            },
        ),
    ]
